export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REQUEST_PRODUCTS_PENDING = 'REQUEST_PRODUCTS_PENDING';
export const REQUEST_PRODUCTS_SUCCESS = 'REQUEST_PRODUCTS_SUCCESS';
export const REQUEST_PRODUCTS_FAILED = 'REQUEST_PRODUCTS_FAILED';
export const BUY_PRODUCT_SUCCESS = 'BUY_PRODUCT_SUCCESS';
export const BUY_PRODUCT_FAILED = 'BUY_PRODUCT_FAILED';
export const REQUEST_TO_BUY_PRODUCT = 'REQUEST_TO_BUY_PRODUCT';